### ISSUE TITLE
教程图片加载不出

### ISSUE THREAD

**Issue by guandongershen** [dunwu/blog#18]
java教程和spring教程有图片加载不出来，图片地址失效

**Comment by dunwu** [comment]
@guandongershen 是哪些文章图片加载不出来呢？

**Comment by guandongershen** [comment]
比如java教程这里，https://dunwu.github.io/javacore/pages/3e1661/#%E7%BB%A7%E6%89%BF%E7%B1%BB%E5%9E%8B

**Comment by dunwu** [comment]
@guandongershen 我看了下，图片是可以加载的，你本机环境是不是访问 github 图片有限制？
